# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random walk Metropolis sampler using Rcpp.
#' @description Implement a random walk Metropolis sampler for generating the standard Laplace distribution
#' @param x0 initial point
#' @param sigma normal distribution variance
#' @param n sample size
#' @return x a random sample of size \code{n} 
#' @return k the number of iterations
#' @examples
#' \dontrun{
#' x0<-25
#' sigma<-0.05
#' n<-2000
#' rwMC(x0,sigma,n)
#' }
#' @export
rwMC <- function(x0, sigma, N) {
    .Call('_SC19087_rwMC', PACKAGE = 'SC19087', x0, sigma, N)
}

