# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Generate normal random numbers 
#' @description Generate normal random numbers using Rcpp
#' @param mu the mean of the normal sample
#' @param sigma the sd of the normal sample
#' @return a random number 
#' @examples
#' \dontrun{
#' rnC <- rnormc(0,1)
#' }
#' @export
rnormc <- function(mu, sigma) {
    .Call('_SC19087_rnormc', PACKAGE = 'SC19087', mu, sigma)
}

